#!/usr/bin/env bash

# Install Homebrew if it isn't installed
if ! command -v brew &> /dev/null; then
    echo "🍺 Installing homebrew..."
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Ensure brew is available in the current session
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo "📦 Updating Homebrew and installing from Brewfile..."
brew update
brew bundle --file="$(pwd -P)/Brewfile"